const fs = require('fs');

let html = fs.readFileSync('schedule.html', 'utf8');

const oldModalRegex = /<!-- Cultivation Plan Modal -->[\s\S]*?<\/script>/;

const newModalAndJS = `<!-- Cultivation Plan Modal -->
    <div id="cultivationPlanModal" style="display: none; position: fixed; top: 0; left: 0; width: 100%; height: 100%; background: rgba(0,0,0,0.85); z-index: 10000; justify-content: center; align-items: center;">
      <div style="background: #fff; color: #333; padding: 20px; border-radius: 8px; width: 98%; max-width: 1200px; box-shadow: 0 4px 15px rgba(0,0,0,0.3); max-height: 95vh; display: flex; flex-direction: column;">
        <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 10px;">
          <h3 style="margin: 0; color: #4CAF50;">🌱 栽培計画作成</h3>
          <span style="cursor: pointer; font-size: 24px; line-height: 1; color: #999;" onclick="document.getElementById('cultivationPlanModal').style.display='none'">×</span>
        </div>
        
        <div style="display: flex; gap: 10px; margin-bottom: 15px; flex-wrap: wrap; background: #f1f8e9; padding: 10px; border-radius: 6px;">
          <div>
            <label style="font-size: 11px; font-weight: bold; color: #555; display: block;">作物</label>
            <input type="text" id="cpCrop" placeholder="キャベツ" style="padding: 6px; border: 1px solid #ccc; border-radius: 4px; font-size: 13px; width: 80px;">
          </div>
          <div>
            <label style="font-size: 11px; font-weight: bold; color: #555; display: block;">品種</label>
            <input type="text" id="cpVariety" placeholder="寒玉" style="padding: 6px; border: 1px solid #ccc; border-radius: 4px; font-size: 13px; width: 80px;">
          </div>
          <div>
            <label style="font-size: 11px; font-weight: bold; color: #555; display: block;">穴数</label>
            <input type="number" id="cpTrayHoles" value="128" oninput="calcCp()" style="padding: 6px; border: 1px solid #ccc; border-radius: 4px; font-size: 13px; width: 60px;">
          </div>
          <div>
            <label style="font-size: 11px; font-weight: bold; color: #555; display: block;">条数</label>
            <input type="number" id="cpRows" value="1" oninput="calcCp()" style="padding: 6px; border: 1px solid #ccc; border-radius: 4px; font-size: 13px; width: 50px;">
          </div>
          <div>
            <label style="font-size: 11px; font-weight: bold; color: #555; display: block;">株間(cm)</label>
            <input type="number" id="cpPlantSpacing" value="30" oninput="calcCp()" style="padding: 6px; border: 1px solid #ccc; border-radius: 4px; font-size: 13px; width: 60px;">
          </div>
          <div>
            <label style="font-size: 11px; font-weight: bold; color: #555; display: block;">畝間(cm)</label>
            <input type="number" id="cpRidgeSpacing" value="150" oninput="calcCp()" style="padding: 6px; border: 1px solid #ccc; border-radius: 4px; font-size: 13px; width: 60px;">
          </div>
          <div>
            <label style="font-size: 11px; font-weight: bold; color: #555; display: block;">収穫係数</label>
            <input type="number" step="0.1" id="cpYieldRate" value="0.9" oninput="calcCp()" style="padding: 6px; border: 1px solid #ccc; border-radius: 4px; font-size: 13px; width: 60px;">
          </div>
          <div style="border-left: 2px solid #ccc; padding-left: 10px; margin-left: 5px;">
            <label style="font-size: 11px; font-weight: bold; color: #e91e63; display: block;">定植面積(a)</label>
            <input type="number" id="cpArea" placeholder="例: 10" oninput="calcCp()" style="padding: 6px; border: 2px solid #e91e63; border-radius: 4px; font-size: 13px; width: 70px; font-weight:bold;">
          </div>
          <div style="flex-grow: 1; display: flex; align-items: flex-end; justify-content: flex-end; gap: 10px;">
             <div id="cpCalcResults" style="font-size: 12px; font-weight: bold; color: #333; padding-bottom: 5px; text-align:right;"></div>
             <button onclick="saveCultivationPlan()" style="background:#2196F3; color:white; border:none; padding:10px 20px; border-radius:5px; font-weight:bold; cursor:pointer;">💾 保存</button>
          </div>
        </div>
        
        <div style="overflow-x: auto; flex: 1; background: #f9f9f9; border: 1px solid #eee;">
          <table id="cpTable" style="width: 100%; border-collapse: collapse; text-align: center; font-size: 11px;">
            <!-- Generated by JS -->
          </table>
        </div>
      </div>
    </div>

    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCjTdBJUXSQOk3fxGk0ESoKErCwdPg0MQ8&libraries=geometry&language=ja"></script>
    <script src="https://unpkg.com/deck.gl@^8.8.0/dist.min.js"></script>
    <script>
      const GAS_URL = "https://script.google.com/macros/s/AKfycbw3yW9QsJMR24PP0k3rASCIpxJCTRFfOIDS3JSQ1_o38zF9DJ2mNvDmwOWpyw6-0K_8/exec";
// --- Cultivation Plan Feature ---
let cpCurrentCalc = { trays: 0, yield: 0 };

function calcCp() {
    const areaA = parseFloat(document.getElementById('cpArea').value) || 0;
    const holes = parseInt(document.getElementById('cpTrayHoles').value) || 128;
    const rows = parseInt(document.getElementById('cpRows').value) || 1;
    const pSpace = (parseFloat(document.getElementById('cpPlantSpacing').value) || 30) / 100;
    const rSpace = (parseFloat(document.getElementById('cpRidgeSpacing').value) || 150) / 100;
    const yieldRate = parseFloat(document.getElementById('cpYieldRate').value) || 0.9;
    
    if (areaA > 0 && pSpace > 0 && rSpace > 0 && rows > 0) {
        const areaM2 = areaA * 100;
        const areaPerPlant = (rSpace / rows) * pSpace;
        const totalPlants = Math.floor(areaM2 / areaPerPlant);
        
        cpCurrentCalc.trays = Math.ceil(totalPlants / holes);
        cpCurrentCalc.yield = Math.floor(totalPlants * yieldRate);
        
        document.getElementById('cpCalcResults').innerHTML = 
            \`株数: <span style="color:#4CAF50">\${totalPlants.toLocaleString()}</span> 株<br>播種: <span style="color:#8D6E63">\${cpCurrentCalc.trays.toLocaleString()}</span> 枚 | 収穫: <span style="color:#FF9800">\${cpCurrentCalc.yield.toLocaleString()}</span> 個\`;
    } else {
        cpCurrentCalc = { trays: 0, yield: 0 };
        document.getElementById('cpCalcResults').innerHTML = '';
    }
    updateCpCellsText();
}

function updateCpCellsText() {
    // 播種セルのテキスト更新
    const sowingCells = document.querySelectorAll('#cpTable td[data-task="sowing"][data-selected="true"]');
    sowingCells.forEach(td => {
        const div = td.querySelector('div');
        div.innerHTML = cpCurrentCalc.trays > 0 ? \`<span style="color:#fff; font-size:10px; display:block; padding-top:10px;">\${cpCurrentCalc.trays}枚</span>\` : '';
    });
    // 収穫セルのテキスト更新
    const harvestCells = document.querySelectorAll('#cpTable td[data-task="harvesting"][data-selected="true"]');
    harvestCells.forEach(td => {
        const div = td.querySelector('div');
        div.innerHTML = cpCurrentCalc.yield > 0 ? \`<span style="color:#fff; font-size:10px; display:block; padding-top:10px;">\${cpCurrentCalc.yield.toLocaleString()}</span>\` : '';
    });
}

function renderCultivationPlanTable() {
    const table = document.getElementById('cpTable');
    if (!table) return;
    
    let tHTML = '<thead><tr><th style="min-width: 60px; position: sticky; left: 0; background: #e3f2fd; z-index: 10; box-shadow: 1px 0 0 #ddd;"></th>';
    for (let m = 1; m <= 12; m++) {
        tHTML += '<th colspan="6" style="border: 1px solid #ddd; background: #f1f8e9; padding: 4px; min-width:150px;">' + m + '月</th>';
    }
    tHTML += '</tr><tr><th style="min-width: 60px; position: sticky; left: 0; background: #e3f2fd; z-index: 10; border-bottom: 2px solid #ccc; box-shadow: 1px 0 0 #ddd;">作業</th>';
    
    const periods = ['上前', '上後', '中前', '中後', '下前', '下後'];
    for (let m = 1; m <= 12; m++) {
        for (let p of periods) {
            tHTML += '<th style="border: 1px solid #ddd; padding: 4px 2px; font-size: 10px; width: 25px; border-bottom: 2px solid #ccc; background: #fafafa; color: #555; writing-mode: vertical-rl; text-orientation: upright;">' + p + '</th>';
        }
    }
    tHTML += '</tr></thead><tbody>';
    
    const tasks = [
        { id: 'sowing', name: '播種', color: '#8D6E63' },
        { id: 'planting', name: '定植', color: '#4CAF50' },
        { id: 'harvesting', name: '収穫', color: '#FF9800' }
    ];
    
    tasks.forEach(task => {
        tHTML += '<tr><td style="position: sticky; left: 0; background: #fff; z-index: 5; font-weight: bold; border: 1px solid #ddd; border-bottom: 2px solid #ccc; box-shadow: 1px 0 0 #ddd;">' + task.name + '</td>';
        for (let m = 1; m <= 12; m++) {
            for (let i = 0; i < periods.length; i++) {
                let br = (i === 5) ? '1px solid #bbb' : '1px solid #eee';
                tHTML += '<td style="border: 1px solid #eee; padding: 0; cursor: pointer; border-right: ' + br + ';" onclick="toggleCpCell(this, \\'' + task.color + '\\')" data-task="' + task.id + '" data-month="' + m + '" data-period="' + i + '"><div style="width: 100%; height: 35px; transition: 0.2s; box-sizing:border-box; text-align:center; overflow:hidden;"></div></td>';
            }
        }
        tHTML += '</tr>';
    });
    
    tHTML += '</tbody>';
    table.innerHTML = tHTML;
}

function toggleCpCell(td, colorHex) {
    const div = td.querySelector('div');
    if (td.dataset.selected === 'true') {
        div.style.backgroundColor = '';
        td.dataset.selected = 'false';
        div.innerHTML = '';
    } else {
        div.style.backgroundColor = colorHex;
        td.dataset.selected = 'true';
    }
    updateCpCellsText();
}

function openCultivationPlanModal() {
    renderCultivationPlanTable();
    calcCp();
    document.getElementById('cultivationPlanModal').style.display = 'flex';
}

async function saveCultivationPlan() {
    const crop = document.getElementById('cpCrop').value.trim();
    const variety = document.getElementById('cpVariety').value.trim();
    const areaA = parseFloat(document.getElementById('cpArea').value) || 0;
    
    if (!crop || !variety || areaA <= 0) {
        alert("作物、品種、定植面積を正しく入力してください。");
        return;
    }
    
    const plan = { 
        crop: crop, 
        variety: variety, 
        areaA: areaA,
        trays: cpCurrentCalc.trays,
        yield: cpCurrentCalc.yield,
        tasks: { sowing: [], planting: [], harvesting: [] } 
    };
    
    const cells = document.querySelectorAll('#cpTable td[data-selected="true"]');
    cells.forEach(cell => {
        const t = cell.dataset.task;
        const m = parseInt(cell.dataset.month, 10);
        const p = parseInt(cell.dataset.period, 10);
        if (plan.tasks[t]) {
            plan.tasks[t].push({ month: m, periodIndex: p });
        }
    });
    
    try {
        const btn = document.querySelector('#cultivationPlanModal button');
        const orgText = btn.innerHTML;
        btn.innerHTML = '送信中...';
        btn.disabled = true;
        
        const res = await fetch(GAS_URL, {
            method: 'POST',
            body: JSON.stringify({
                action: 'saveCultivationPlan',
                planData: plan
            })
        });
        const json = await res.json();
        
        btn.innerHTML = orgText;
        btn.disabled = false;
        
        if (json.status === 'success') {
            alert("【" + crop + " / " + variety + "】の栽培計画をシステムに保存しました！");
            document.getElementById('cultivationPlanModal').style.display = 'none';
        } else {
            alert("保存エラー: " + json.message);
        }
    } catch(e) {
        alert("通信エラー: " + e.message);
        const btn = document.querySelector('#cultivationPlanModal button');
        btn.innerHTML = '💾 保存';
        btn.disabled = false;
    }
}
</script>`;

if (html.match(oldModalRegex)) {
    html = html.replace(oldModalRegex, newModalAndJS);
    fs.writeFileSync('schedule.html', html);
    console.log("Successfully replaced modal and JS in schedule.html");
} else {
    console.log("Could not find the target regex in schedule.html");
}
